stages:
  download-images:
    cmd: python scripts/download-images.py datasets/watch-faces.json
    deps:
    - scripts/download-images.py
    - datasets/watch-faces.json
    outs:
    - datasets/train:
        persist: true
    - datasets/test:
        persist: true
    - datasets/val:
       persist: true
    - datasets/watch-faces-local.json
# TODO stage for generating detection dataset from label-studio dataset?
  train-detector:
    cmd: >- 
      python watch_recognition/watch_recognition/train/object_detection_task.py 
      --epochs ${detector.epochs} 
      --batch-size ${detector.batch-size} 
      --confidence-threshold ${detector.confidence-threshold} 
      --seed ${seed}
      --fine-tune-from-checkpoint
    params:
      - detector.epochs
      - detector.batch-size
      - seed
    deps:
      - datasets/train
      - datasets/test
      - datasets/val
      - datasets/watch-faces-local.json
      - watch_recognition/watch_recognition/train/object_detection_task.py
      - checkpoints/detector/
    metrics:
      - metrics/detector.json:
          cache: false
    plots:
      - metrics/detector/scalars:
          cache: false
    outs:
      - example_predictions/detector/test-image.jpg
      - models/detector/:
          persist: true
  eval-detector:
    cmd: python watch_recognition/watch_recognition/eval/object_detection_eval.py
    deps:
      - models/detector/
      - watch_recognition/watch_recognition/eval/object_detection_eval.py
    outs:
      - example_predictions/detector/train_0.jpg
      - example_predictions/detector/train_1.jpg
      - example_predictions/detector/train_2.jpg
      - example_predictions/detector/train_3.jpg
      - example_predictions/detector/train_4.jpg
      - example_predictions/detector/val_0.jpg
      - example_predictions/detector/val_1.jpg
      - example_predictions/detector/val_2.jpg
      - example_predictions/detector/val_3.jpg
    metrics:
      - metrics/detector/coco_train.json:
          cache: false
      - metrics/detector/coco_val.json:
          cache: false
    plots:
      - metrics/detector/PR-IoU@0.50_train.tsv:
          x: Recall
          y: Precision
          title: Train PR-IoU@0.50
          cache: false
      - metrics/detector/PR-IoU@0.75_train.tsv:
          x: Recall
          y: Precision
          title: Train PR-IoU@0.75
          cache: false
      - metrics/detector/PR-IoU@0.95_train.tsv:
          x: Recall
          y: Precision
          title: Train PR-IoU@0.95
          cache: false
      - metrics/detector/PR-IoU@0.50_val.tsv:
          x: Recall
          y: Precision
          title: Val PR-IoU@0.50
          cache: false
      - metrics/detector/PR-IoU@0.75_val.tsv:
          x: Recall
          y: Precision
          title: Val PR-IoU@0.75
          cache: false
      - metrics/detector/PR-IoU@0.95_val.tsv:
          x: Recall
          y: Precision
          title: Val PR-IoU@0.95
          cache: false
  train-keypoint:
    cmd: >-
      python watch_recognition/watch_recognition/train/heatmap_regression_task.py
      --epochs ${keypoint.epochs}
      --batch-size ${keypoint.batch-size}
      --confidence-threshold ${keypoint.confidence-threshold}
      --seed ${seed}
      --fine-tune-from-checkpoint
    params:
      - keypoint
      - seed
    deps:
      - datasets/train
      - datasets/test
      - datasets/val
      - datasets/watch-faces-local.json
      - watch_recognition/watch_recognition/train/heatmap_regression_task.py
      - checkpoints/keypoint/
    metrics:
      - metrics/keypoint.json:
          cache: false
    plots:
      - metrics/keypoint/scalars/:
          cache: false
    outs:
      - example_predictions/keypoint/test-image-2.jpg:
          persist: true
      - models/keypoint/:
          persist: true
  eval-keypoint:
    cmd: python watch_recognition/watch_recognition/eval/keypoint_detection_eval.py --kp-confidence-threshold ${keypoint.confidence-threshold}
    deps:
      - models/keypoint/
      - models/detector/
      - watch_recognition/watch_recognition/eval/keypoint_detection_eval.py
    outs:
      - example_predictions/keypoint/train_0.jpg
      - example_predictions/keypoint/train_1.jpg
      - example_predictions/keypoint/train_2.jpg
      - example_predictions/keypoint/train_3.jpg
      - example_predictions/keypoint/train_4.jpg
      - example_predictions/keypoint/val_0.jpg
      - example_predictions/keypoint/val_1.jpg
      - example_predictions/keypoint/val_2.jpg
      - example_predictions/keypoint/val_3.jpg
      - example_predictions/keypoint/val_4.jpg
    metrics:
      - metrics/keypoint/coco_train.json:
          cache: false
      - metrics/keypoint/coco_val.json:
          cache: false
  update-metrics:
      cmd: python scripts/update-metrics-table-and-graph.py
      deps:
        - metrics