seed: 42

detector:
  epochs: 100
  batch-size: 16
  confidence-threshold: 0.5

keypoint:
  epochs: 100
  batch-size: 32
  confidence-threshold: 0.5

segmentation:
  epochs: 100
  batch-size: 32
  confidence-threshold: 0.5
