seed: 42

detector:
  epochs: 50
  batch-size: 16
  confidence-threshold: 0.5

keypoint:
  epochs: 25
  batch-size: 16
  confidence-threshold: 0.5

segmentation:
  epochs: 25
  batch-size: 16
  confidence-threshold: 0.5
