seed: 42

detector:
  epochs: 1
  batch-size: 4
  confidence-threshold: 0.5

keypoint:
  epochs: 1
  batch-size: 8
  confidence-threshold: 0.5

segmentation:
  epochs: 1
  batch-size: 8
  confidence-threshold: 0.5
